version: '3'
services:
  webapp:
    build: ./webapp
    restart: always
    depends_on:
      - redis
  webapp2:
    build: ./webapp
    restart: always
    depends_on:
      - redis
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "hiredis"]
    container_name: redis-master
    ports:
      - "6379:6379"
  nginx:
    build: ./nginx
    restart: always
    depends_on:
      - webapp
      - webapp2
    ports:
      - "80:80"