version: '3'
services:
  webapp:
    build: ./webapp
    restart: always
    depends_on:
      - redis
    ports:
      - "8080:8080"
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "hiredis"]
    container_name: redis-master
    ports:
      - "6379:6379"